### ISSUE TITLE
算Bug吗？

### ISSUE THREAD

**Issue by Eggku** [KaringX/clashmi#23]
iPhone iOS 16.6.1 

手机在使用数据+WiFi的情况下开启代理后使用speedtest.cn或speedtest.net 无法获取当前本机的IP。测速不正常。
当手机飞行模式使用WiFi的情况下开启代理后使用speedtest.cn或speedtest.net 正确获取当前本机的IP。 测速正常能跑满。

iOS设备​
1.进入 设置 > 蜂窝网络 > 关闭“无线局域网助理”。
2.进入 设置 > 蜂窝网络 > 选择需要限制的应用，设置为“仅WLAN”。

开启代理后按照上面的2点设置后使用WiFi无法上网。

**请问可以在WiFi+数据的情况下优先使用WiFi吗？**

使用的Tun和DNS配置：
 ```
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
    
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
```
