### ISSUE TITLE
ipv6 节点连接问题

### ISSUE THREAD

**Issue by AceTaffy812** [KaringX/clashmi#47]
版本: v1.0.1.55
平台: ios/android

问题情景：
订阅导入，假设节点的 server 字段是一个域名，这个域名有且仅有一个 AAAA 记录。
当前用户连接的网络为双栈，希望能根据这个 AAAA 记录的地址成功连接到节点服务器。
**但是实际上会直接失败，必须要手动开启 `核心设置 - IPV6` 才能使用 v6 节点。**

希望优化以上问题。

期望效果：不需要特别开启IPv6即可连接到IPv6节点。

mihomo 内核有关 ipv6 的行为：

```yaml
ipv6: true # 默认是 true, 如果这个设置为 false, 就会将下方 dns ipv6 强制关闭
dns:  
  ipv6: true # 如果这个被设置为 false, 就会导致节点 ipv6 解析为空结果，导致无法连接到节点
```
如果担心用户的网络没有双栈，一些国内应用DIRECT v6连接失败的话，只需要控制 tun 的地址，不要为 tun 添加 IPv6 地址就可以了，没有必要将所 有 IPv6 一刀切关闭。
